### ISSUE TITLE
How can I get count of alerts sent over a time period.

### ISSUE THREAD

**Issue by atulkhaire** [livingsocial/rearview#34]
Hi,

Can someone help me understand the significance/purpose of 'job_errors' table ?

Is there a way to compute no. of alerts triggered by a monitor over a time interval ? 
This interval can be a day, a week or a month.

I feel this can be achieved from 'job_errors' table because I see entries in this table with status 'failed'. But this does not convince me much because in my case the no. of alerts generated by a monitor till now are more than the no. of entries in 'job_errors' with status='failed' for that monitor. 

I have been digging into code/logs to understand the purpose of  'Job_errors' table but have not reached to any conclusion yet. 

Thanks,

**Comment by steveakers** [comment]
We've been talking about this recently. The job_errors table is really tracking job state (how long was it in failed, then how long in success, etc.) Knowing the state would be usefully for an alert timeline feature, which we once had, but does not help you know how often there was an actual alert. We've been discussing the possibility of adding a job_alerts table that would exist purely to track the number of alerts (timing, alert message, etc.) This would also serve to fill the alert history tab with the actual alerts rather than just the first alert (or state change). Does that make sense?

**Comment by talbright** [comment]
@steveakers is correct on the interpretation of the data model, and the difference between tracking a job state and tracking alerts. That being said, you could still come up with an algorithm to get what you want by using the job_errors table. The significant gotcha is that new entries in job_errors are not created as long as the monitor is continuously in an alert state. You can determine how many alerts were triggered though by comparing the created_at and updated_at field times, and understanding that an alert will be sent out at the most once every 60 minutes.

**Comment by talbright** [comment]
Assuming this answered your questions...
