### ISSUE TITLE
Graphite URL generation

### ISSUE THREAD

**Issue by zampettim** [livingsocial/rearview#4]
How is the URL for obtaining the data from Graphite built? I see how the hostname and auth information is supplied, but the URL that hits my Graphite servers doesn't seem to be correct. It seems to be missing some of the base parameters.

I'm not a Scala guy, so its a bit hard to figure out how that is being generated.

**Comment by steveakers** [comment]
In app/rearview/monitor/Monitor.scala here http://bit.ly/16S1H9h it's:

Global.graphiteHost + """/render?from=%s&until=%s&format=raw""".format(from, to) + "&target=" + encMetrics.mkString("&target=")

So that's host url + render string + from and to date (based on minutes back in monitor) + targets (based on metrics entered into monitor). Does that make sense
