### ISSUE TITLE
Validation Failure - graphite can not be reached.

### ISSUE THREAD

**Issue by yl2chen** [livingsocial/rearview#44]
Hi Rearview team,

I have the following configuration for graphite in config/initializers/rearview.rb

`config.graphite_connection = {url: "https://www.hostedgraphite.com/{Hosted Graphite Access Key}/graphite"}`

When I run the instructed command to check verifications (rake RAILS_ENV=production rearview:config:verify) I get the following output at the end.

`validating...FAILED
Graphite connection graphite cannot be reached`

I have verified that the graphite url I provided is working (e.g., appending '/render' at the end will get you an empty graph).

Any ideas why it is failing the validation?

Thanks in advance

**Comment by talbright** [comment]
The syntax does not look like valid ruby. It should be something like:

``` ruby
config.graphite_connection = { url: 'http://graphite.mycom.com' }
```

**Comment by yl2chen** [comment]
@talbright sorry, that was just a typo in the question posted (edited), that is not the cause of my problem.

**Comment by talbright** [comment]
Please do the following command, and report back to me the complete output.

**DO NOT POST YOUR KEY**

```
curl -v https://www.hostedgraphite.com/{Hosted Graphite Access Key}/graphite/render
```

**Comment by yl2chen** [comment]
```
$ curl -v https://www.hostedgraphite.com/{Hosted Graphite Access Key}/graphite/render
* Adding handle: conn: 0x7fd15b80a600
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fd15b80a600) send_pipe: 1, recv_pipe: 0
* About to connect() to www.hostedgraphite.com port 443 (#0)
*   Trying 188.40.120.79...
* Connected to www.hostedgraphite.com (188.40.120.79) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: *.hostedgraphite.com
* Server certificate: RapidSSL CA
* Server certificate: GeoTrust Global CA
* Server certificate: Equifax Secure Certificate Authority
> GET /{Hosted Graphite Access Key}/graphite/render HTTP/1.1
> User-Agent: curl/7.30.0
> Host: www.hostedgraphite.com
> Accept: */*
>
< HTTP/1.1 200 OK
* Server Fluttershy is not blacklisted
< Server: Fluttershy
< Vary: Cookie
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Content-Type: image/png
< Access-Control-Allow-Headers: origin, authorization, accept
< Transfer-Encoding: chunked
< Date: Thu, 19 Jun 2014 18:22:19 GMT
<
�PNG

IHDRJH�bKGD�������IDATx���=h�W���1zմ56�W�T�
\>h�#�����0IG��Υ�՞��t��������_f�����KVlO�����b�To�I;�G_e��WNښ����w2��D�K������H�df�?�}S>��r9����0�t�9o<ϓ��ݗ�/[�rR��-R�&j�����J�3���iO�n���sl�=a����nH��O_j��i}x)�nɼe�՞ʖ�^ʓ�6�ڟ������d�7>*��>
* Connection #0 to host www.hostedgraphite.com left intact
���}����B�$��i(�`�}��;Fځ�<[�JSJ�h��F՝���Q����yp0I����:�T�z/�+ؗ)�ˣ�i=�u�2x~�R8�ǻ�v&�{��G���ڞ���cIEND�B`�
```

**Comment by yl2chen** [comment]
I have a feeling it could be due to the check that is performed here
https://github.com/livingsocial/rearview-engine/blob/master/lib/graphite/client.rb#L38

it specifically checks for `response.headers['content-length'].to_i > 0` which I didn't see in the response header

**Comment by talbright** [comment]
Good call, this is the method I was looking at as well. I was actually wondering if perhaps the hosted graphite service doesn't respond with a png. Checking for a png might seem overly strict, but I wanted to count on something besides a simple 200, as that would not being saying much about the validity of the url. Granted the url the check uses includes /render, which does add some specificity.

The reason there's no content-length header is because the server is using chunked encoding:

http://en.wikipedia.org/wiki/Chunked_transfer_encoding

So my validation should probably just check for non-zero body size instead of content-length.

That being said, in this case you can probably consider this simply as a warning. I don't force configuration to pass in order for rearview to boot up (unless you use the config.verify option).
